### ISSUE TITLE
crash on arena pick

### ISSUE THREAD

**Issue by Spotegg** [corlettb/HDTAHPluginHAPlugin#3]
On 7th turn the game crashed. I play in windowed mode 1680*1050, deck tracker and arena helper and this plugin have newest versions.

I have 2 logs - one when it happened, and second - after i tried to resume arena.

1st
###### #### 14.10.2015 13:33:39

System.NullReferenceException: Object reference not set to an instance of an object.
   at HDTAHPluginHAPlugin.HDTAHPluginHAPlugin.<CardPicked>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[13:31:25] DeckList: Set active deck to: Patron 73% (Warrior)
[13:31:25] Tracker: Switched to deck: Patron 73%
[13:31:25] Game: -------- Reset ---------
[13:31:25] OpponentSecrets: Cleared secrets
[13:31:25] : Checking for duplicate matches...
[13:31:25] GameEventHandler: Reset constructed importing
[13:31:25] BackupManager: Running BackupManager
[13:31:25] BackupManager: Backup for today already exists
[13:31:26] PluginManager: Loading Plugins...
[13:31:26] PluginWrapper: Loading Arena Helper
[13:31:26] : HDTAHPluginHAPlugin constructor
[13:31:26] : HearthArena cards loaded
[13:31:26] : Found: HDTAHPluginHAPlugin
[13:31:26] PluginWrapper: Enabled Arena Helper
[13:31:26] Helper: Checking for LIVE updates...
[13:31:26] Helper: Current version: 0.12.1.0
[13:31:26] LogReader: Current region: EU
[13:31:26] UpdateOverlay: Refreshed overlay topmost status
[13:31:26] Helper: Latest LIVE version: 0.12.1.0
[13:31:26] Game: Set CurrentGameMode to Ranked
[13:31:26] Game: Set CurrentGameMode to Ranked
[13:31:26] Game: Set CurrentGameMode to Arena
[13:31:27] : Resuming Arena
[13:31:27] : HearthArena picklist: -
[13:31:27] : State: SearchHeroes
[13:31:29] : New Arena: Arena 14-10 01:31
[13:31:31] UpdateOverlay: Refreshed overlay topmost status
[13:31:35] : Heroes Detected: Rogue, Mage, Shaman
[13:31:41] : Created new arena deck: Mage
[13:31:44] : Hero Picked: Mage, id: 3
[13:31:45] : Making heartharena call to http://draft.heartharena.com/arena/option-multi-score/3/-/138-901-900...
[13:31:45] : ... Call took 489ms
[13:31:47] UpdateOverlay: Refreshed overlay topmost status
[13:31:51] UpdateOverlay: Refreshed overlay topmost status
[13:32:06] : Card Picked: Polymorph: Boar
[13:32:06] : Added new card to arena deck: AT_005 (1/30)
[13:32:07] : Making heartharena call to http://draft.heartharena.com/arena/option-multi-score/3/901/463-858-405...
[13:32:07] : ... Call took 406ms
[13:32:21] : Added new card to arena deck: CS2_227 (2/30)
[13:32:22] : Card Picked: Venture Co. Mercenary
[13:32:24] : Making heartharena call to http://draft.heartharena.com/arena/option-multi-score/3/901-463/273-469-276...
[13:32:24] : ... Call took 356ms
[13:32:43] : Added new card to arena deck: NEW1_018 (3/30)
[13:32:44] : Card Picked: Bloodsail Raider
[13:32:45] : Making heartharena call to http://draft.heartharena.com/arena/option-multi-score/3/901-463-273/873-251-291...
[13:32:45] : ... Call took 330ms
[13:32:57] : Card Picked: Boneguard Lieutenant
[13:32:57] : Added new card to arena deck: AT_089 (4/30)
[13:32:58] : Making heartharena call to http://draft.heartharena.com/arena/option-multi-score/3/901-463-273-873/471-972-372...
[13:32:59] : ... Call took 365ms
[13:33:10] : Card Picked: Evil Heckler
[13:33:10] : Added new card to arena deck: AT_114 (5/30)
[13:33:12] : Making heartharena call to http://draft.heartharena.com/arena/option-multi-score/3/901-463-273-873-972/169-292-384...
[13:33:12] : ... Call took 372ms
[13:33:18] : Added new card to arena deck: CS2_025 (6/30)
[13:33:20] : Card Picked: Arcane Explosion
[13:33:20] : Making heartharena call to http://draft.heartharena.com/arena/option-multi-score/3/901-463-273-873-972-169/869-899-279...
[13:33:21] : ... Call took 364ms
[13:33:35] : Card Picked: Flame Lance
[13:33:35] : Added new card to arena deck: AT_001 (7/30)
[13:33:36] : Making heartharena call to http://draft.heartharena.com/arena/option-multi-score/3/901-463-273-873-972-169-899/372-754-253...
[13:33:37] : ... Call took 370ms
###### #### 14.10.2015 13:33:55

System.NullReferenceException: Object reference not set to an instance of an object.
   at HDTAHPluginHAPlugin.HDTAHPluginHAPlugin.cardToHAID(Card card)
   at HDTAHPluginHAPlugin.HDTAHPluginHAPlugin.<ResumeArena>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[13:33:50] DeckList: Set active deck to: Patron 73% (Warrior)
[13:33:51] Tracker: Switched to deck: Patron 73%
[13:33:51] Game: -------- Reset ---------
[13:33:51] OpponentSecrets: Cleared secrets
[13:33:51] : Checking for duplicate matches...
[13:33:51] GameEventHandler: Reset constructed importing
[13:33:51] BackupManager: Running BackupManager
[13:33:51] BackupManager: Backup for today already exists
[13:33:51] PluginManager: Loading Plugins...
[13:33:51] PluginWrapper: Loading Arena Helper
[13:33:51] : HDTAHPluginHAPlugin constructor
[13:33:51] : HearthArena cards loaded
[13:33:51] : Found: HDTAHPluginHAPlugin
[13:33:51] PluginWrapper: Enabled Arena Helper
[13:33:51] Helper: Checking for LIVE updates...
[13:33:51] Helper: Current version: 0.12.1.0
[13:33:51] LogReader: Current region: EU
[13:33:51] UpdateOverlay: Refreshed overlay topmost status
[13:33:52] Helper: Latest LIVE version: 0.12.1.0
[13:33:52] Game: Set CurrentGameMode to Ranked
[13:33:52] Game: Set CurrentGameMode to Ranked
[13:33:52] Game: Set CurrentGameMode to Arena
[13:33:52] : Created new arena deck: Mage
[13:33:52] : Added new card to arena deck: AT_005 (1/30)
[13:33:52] : Added new card to arena deck: CS2_227 (2/30)
[13:33:52] : Added new card to arena deck: NEW1_018 (3/30)
[13:33:52] : Added new card to arena deck: AT_089 (4/30)
[13:33:52] : Added new card to arena deck: AT_114 (5/30)
[13:33:52] : Added new card to arena deck: CS2_025 (6/30)
[13:33:52] : Added new card to arena deck: AT_001 (7/30)
[13:33:52] UpdateOverlay: Refreshed overlay topmost status
[13:33:55] : Resuming Arena
[13:33:55] : Detected hero: Rogue
[13:33:55] : Detected hero: Mage
[13:33:55] : Detected hero: Shaman
[13:33:55] : Picked hero: Mage, id: 3
[13:33:55] : Polymorph: Boar
[13:33:55] : Venture Co. Mercenary
[13:33:55] : Bloodsail Raider
[13:33:55] : Boneguard Lieutenant
[13:33:55] : Evil Heckler
[13:33:55] : Arcane Explosion
[13:33:55] : Flame Lance

2nd
###### #### 14.10.2015 13:35:39

System.NullReferenceException: Object reference not set to an instance of an object.
   at HDTAHPluginHAPlugin.HDTAHPluginHAPlugin.cardToHAID(Card card)
   at HDTAHPluginHAPlugin.HDTAHPluginHAPlugin.<ResumeArena>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[13:35:15] DeckList: Set active deck to: Patron 73% (Warrior)
[13:35:16] Tracker: Switched to deck: Patron 73%
[13:35:16] Game: -------- Reset ---------
[13:35:16] OpponentSecrets: Cleared secrets
[13:35:16] : Checking for duplicate matches...
[13:35:16] GameEventHandler: Reset constructed importing
[13:35:16] BackupManager: Running BackupManager
[13:35:16] BackupManager: Backup for today already exists
[13:35:16] PluginManager: Loading Plugins...
[13:35:16] PluginWrapper: Loading Arena Helper
[13:35:16] : HDTAHPluginHAPlugin constructor
[13:35:16] : HearthArena cards loaded
[13:35:16] : Found: HDTAHPluginHAPlugin
[13:35:16] PluginWrapper: Enabled Arena Helper
[13:35:16] Helper: Checking for LIVE updates...
[13:35:16] Helper: Current version: 0.12.1.0
[13:35:16] LogReader: Current region: EU
[13:35:16] UpdateOverlay: Refreshed overlay topmost status
[13:35:16] Helper: Latest LIVE version: 0.12.1.0
[13:35:17] Game: Set CurrentGameMode to Ranked
[13:35:17] Game: Set CurrentGameMode to Ranked
[13:35:17] Game: Set CurrentGameMode to Arena
[13:35:17] : Created new arena deck: Mage
[13:35:17] : Added new card to arena deck: AT_005 (1/30)
[13:35:17] : Added new card to arena deck: CS2_227 (2/30)
[13:35:17] : Added new card to arena deck: NEW1_018 (3/30)
[13:35:17] : Added new card to arena deck: AT_089 (4/30)
[13:35:17] : Added new card to arena deck: AT_114 (5/30)
[13:35:17] : Added new card to arena deck: CS2_025 (6/30)
[13:35:17] : Added new card to arena deck: AT_001 (7/30)
[13:35:18] UpdateOverlay: Refreshed overlay topmost status
[13:35:36] : Added new card to arena deck: EX1_096 (8/30)
[13:35:39] : Resuming Arena
[13:35:39] : Detected hero: Rogue
[13:35:39] : Detected hero: Mage
[13:35:39] : Detected hero: Shaman
[13:35:39] : Picked hero: Mage, id: 3
[13:35:39] : Polymorph: Boar
[13:35:39] : Venture Co. Mercenary
[13:35:39] : Bloodsail Raider
[13:35:39] : Boneguard Lieutenant
[13:35:39] : Evil Heckler
[13:35:39] : Arcane Explosion
[13:35:39] : Flame Lance

**Comment by TheGoblinHero** [comment]
Have the same problem. Here's mine log:

########## 03.11.2015 19:50:53 ##########
System.NullReferenceException: Object reference not set to an instance of an object.
   at HDTAHPluginHAPlugin.HDTAHPluginHAPlugin.cardToHAID(Card card)
   at HDTAHPluginHAPlugin.HDTAHPluginHAPlugin.<ResumeArena>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[19:50:47] DeckList: Set active deck to: Arena 2015-11-03 19:39 (Mage)
[19:50:48] Tracker: Switched to deck: Arena 2015-11-03 19:39
[19:50:48] Game: -------- Reset ---------
[19:50:48] OpponentSecrets: Cleared secrets
[19:50:49] : Checking for duplicate matches...
[19:50:49] GameEventHandler: Reset constructed importing
[19:50:49] BackupManager: Running BackupManager
[19:50:49] BackupManager: Backup for today already exists
[19:50:49] PluginManager: Loading Plugins...
[19:50:49] PluginWrapper: Loading Collection Tracker
[19:50:49] PluginWrapper: Enabled Collection Tracker
[19:50:49] PluginWrapper: Loading Arena Helper
[19:50:49] : HDTAHPluginHAPlugin constructor
[19:50:49] : HearthArena cards loaded
[19:50:49] : Found: HDTAHPluginHAPlugin
[19:50:49] PluginWrapper: Enabled Arena Helper
[19:50:49] Helper: Checking for LIVE updates...
[19:50:49] Helper: Current version: 0.13.1.0
[19:50:49] LogReader: Current region: EU
[19:50:49] UpdateOverlay: Refreshed overlay topmost status
[19:50:49] GameEventHandler: Reset constructed importing
[19:50:49] Game: Set CurrentGameMode to Arena
[19:50:49] : Created new arena deck: Mage
[19:50:49] : Created new arena deck: Mage
[19:50:49] : Added new card to arena deck: EX1_594 (1/30)
[19:50:49] : Added new card to arena deck: EX1_015 (2/30)
[19:50:49] : Added new card to arena deck: AT_001 (3/30)
[19:50:49] : Added new card to arena deck: CS2_119 (4/30)
[19:50:49] : Added new card to arena deck: CS2_222 (5/30)
[19:50:49] : Added new card to arena deck: GVG_078 (6/30)
[19:50:49] : Added new card to arena deck: AT_007 (7/30)
[19:50:49] : Added new card to arena deck: FP1_001 (8/30)
[19:50:49] : Added new card to arena deck: GVG_090 (9/30)
[19:50:49] : Added new card to arena deck: FP1_012 (10/30)
[19:50:49] : Added new card to arena deck: EX1_032 (11/30)
[19:50:49] : Added new card to arena deck: CS2_029 (12/30)
[19:50:49] : Added new card to arena deck: AT_095 (13/30)
[19:50:49] : Added new card to arena deck: CS2_117 (14/30)
[19:50:49] : Added new card to arena deck: NEW1_012 (15/30)
[19:50:49] : Added new card to arena deck: EX1_082 (16/30)
[19:50:49] : Added new card to arena deck: CS2_222 (17/30)
[19:50:49] : Added new card to arena deck: CS2_120 (18/30)
[19:50:49] : Added new card to arena deck: CS2_022 (19/30)
[19:50:49] : Added new card to arena deck: AT_110 (20/30)
[19:50:49] : Added new card to arena deck: EX1_170 (21/30)
[19:50:49] : Added new card to arena deck: CS2_029 (22/30)
[19:50:49] : Added new card to arena deck: CS2_024 (23/30)
[19:50:49] : Added new card to arena deck: FP1_004 (24/30)
[19:50:49] : Added new card to arena deck: EX1_162 (25/30)
[19:50:49] : Added new card to arena deck: CS2_024 (26/30)
[19:50:49] : Added new card to arena deck: CS2_179 (27/30)
[19:50:49] : Added new card to arena deck: GVG_079 (28/30)
[19:50:49] : Added new card to arena deck: GVG_044 (29/30)
[19:50:49] : Added new card to arena deck: AT_086 (30/30)
[19:50:49] : Found complete arena deck!
[19:50:49] : ...but we already have that one. Discarding.
[19:50:49] Helper: Latest LIVE version: 0.13.1.0
[19:50:53] : Resuming Arena
[19:50:53] : Detected hero: Warlock
[19:50:53] : Detected hero: Mage
[19:50:53] : Detected hero: Warrior
[19:50:53] : Picked hero: Mage, id: 3
[19:50:53] : Vaporize
[19:50:53] : Novice Engineer
[19:50:53] : Flame Lance
[19:50:53] : Oasis Snapjaw
[19:50:53] : Stormwind Champion
[19:50:53] : Mechanical Yeti

**Comment by corlettb** [comment]
The problem here is that the card selection detection from arenahelper isn't perfect. It sometimes misses the selected card. Arenahelper then registers the selected card as "". I suggested that in the case of it missing the selection it should asked the user what was selected.

I could make it not crash but the draft would be screwed after this has happnened as heartharena needs to know all the cards in the deck so far.

**Comment by TheGoblinHero** [comment]
I understand. Please, make it not crash and continue drafting. Yes, one card would be missing, but it's better than nothing.
